# we use the opentelemetry influxDB plugin instead of telegraf, both are fine
[global_tags]
user = "admin"

[agent]
interval = "5s"
metric_batch_size = 1000
metric_buffer_limit = 10000
debug = true

# see: https://github.com/influxdata/telegraf/blob/release-1.21/plugins/inputs/opentelemetry/README.md
[[inputs.opentelemetry]]
service_address = "0.0.0.0:4317"
timeout = "5s"
metrics_schema = "prometheus-v1"


[[outputs.influxdb_v2]]
urls = ["http://influxdb:8086"]
token = "specialToken000"
organization = "my-org"
bucket = "my-bucket"

# see: https://github.com/influxdata/telegraf/blob/master/plugins/aggregators/histogram/README.md
[[aggregators.histogram]]
period = "10s"
drop_original = false
reset = false
cumulative = true
