version: "3.9"
services:
  otel-collector:
    image: otel/opentelemetry-collector
    command: [ "--config=/etc/otel-config.yml" ]
    volumes:
      - ./otel-config.yml:/etc/otel-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "4317:4317"   # otlp receiver
      - "4318:4318"   # otlp http