version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/app
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - SPRING_RABBITMQ_HOST=rabbit
    depends_on:
      rabbit:
        condition: service_healthy

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 3s
