version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/app
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - OTEL_HOST=otel-collector
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector
    container_name: "demo-otel-collector"
    command: [ "--config=/etc/otel-config.yml" ]
    volumes:
      - ./docker/opentelemetry/otel-config.yml:/etc/otel-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "4317:4317"   # otlp receiver
      - "4318:4318"   # otlp http
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: "demo-prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.1.8
    container_name: "demo-grafana"
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=TRUE
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
      - GF_INSTALL_PLUGINS=https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/releases/download/v4.0.2/novatec-sdg-panel.zip;novatec-sdg-panel
    volumes:
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3030:3000"
    depends_on:
      - prometheus