# my global config
global:
  scrape_interval: 1s

scrape_configs:
  - job_name: demo
    # scrape_interval is defined by the configured global (15s).
    # scrape_timeout is defined by the global default (10s).

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['otel-collector:4318']
