datasources:
  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    isDefault: true
#    secureJsonData:
#      token: "b8cVNwJf16kmSR_gKR-og891kiZ1lvLIpmJCszJSh5G6mrSB7dQusSKSVTAikvn5tGl3IUhkgpAj3RdjmLqZDQ=="
#    jsonData:
#      version: Flux
#      organization: "ORDIX_AG"
#      defaultBucket: "TestBucket"