apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    orgId: 1
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    jsonData:
      version: Flux
      organization: $DOCKER_INFLUXDB_INIT_ORG
      defaultBucket: $DOCKER_INFLUXDB_INIT_BUCKET