global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'otel-collector-metrics'
    static_configs:
      - targets: ['otel-collector:8889'] #use service inside docker-compose as host